import type { Metadata } from "next";
import { Alegreya_Sans_SC } from "next/font/google";
import "./globals.css";
import Header from "./assets/components/Header";

const inter = Alegreya_Sans_SC({ 
  weight: "400",
  display: "swap",
  subsets: ["latin"],
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
